name: groomely_seller
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  intl: ^0.17.0
  dio: ^5.1.1
  shared_preferences:
  table_calendar:
  flutter_bloc: ^8.1.2
  shimmer: ^2.0.0
  pdf:
  printing:
  image_picker: ^0.8.9
  email_validator: ^2.1.16
  google_fonts: ^5.1.0
  flutter_riverpod: ^2.3.6
  provider: ^6.0.5
  hooks_riverpod: ^2.3.6
  hive: ^2.2.3
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  equatable: ^2.0.5



dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterLight.ttf
          weight: 300
    - family: Oxygen
      fonts: 
        - asset: assets/fonts/OxygenRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
